package taifex.model.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import taifex.model.entity.TbFutureIns;
import taifex.model.entity.TbFutureInsExample;
import taifex.model.entity.TbFutureInsKey;

public interface TbFutureInsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int countByExample(TbFutureInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByExample(TbFutureInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByPrimaryKey(TbFutureInsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insert(TbFutureIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insertSelective(TbFutureIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    List<TbFutureIns> selectByExample(TbFutureInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    TbFutureIns selectByPrimaryKey(TbFutureInsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbFutureIns record, @Param("example") TbFutureInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExample(@Param("record") TbFutureIns record, @Param("example") TbFutureInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKeySelective(TbFutureIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKey(TbFutureIns record);
}