package taifex.model.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import taifex.model.entity.TbFutureHis;
import taifex.model.entity.TbFutureHisExample;
import taifex.model.entity.TbFutureHisKey;

public interface TbFutureHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int countByExample(TbFutureHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByExample(TbFutureHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByPrimaryKey(TbFutureHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insert(TbFutureHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insertSelective(TbFutureHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    List<TbFutureHis> selectByExample(TbFutureHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    TbFutureHis selectByPrimaryKey(TbFutureHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbFutureHis record, @Param("example") TbFutureHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExample(@Param("record") TbFutureHis record, @Param("example") TbFutureHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKeySelective(TbFutureHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_FUTURE_HIS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKey(TbFutureHis record);
}