package taifex.model.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import taifex.model.entity.TbFutureBigtraderOi;
import taifex.model.entity.TbFutureBigtraderOiExample;
import taifex.model.entity.TbFutureBigtraderOiKey;

public interface TbFutureBigtraderOiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int countByExample(TbFutureBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByExample(TbFutureBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByPrimaryKey(TbFutureBigtraderOiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insert(TbFutureBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insertSelective(TbFutureBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    List<TbFutureBigtraderOi> selectByExample(TbFutureBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    TbFutureBigtraderOi selectByPrimaryKey(TbFutureBigtraderOiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbFutureBigtraderOi record, @Param("example") TbFutureBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExample(@Param("record") TbFutureBigtraderOi record, @Param("example") TbFutureBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKeySelective(TbFutureBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKey(TbFutureBigtraderOi record);
}