package taifex.model.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import taifex.model.entity.TbOpBigtraderOi;
import taifex.model.entity.TbOpBigtraderOiExample;
import taifex.model.entity.TbOpBigtraderOiKey;

public interface TbOpBigtraderOiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int countByExample(TbOpBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByExample(TbOpBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByPrimaryKey(TbOpBigtraderOiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insert(TbOpBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insertSelective(TbOpBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    List<TbOpBigtraderOi> selectByExample(TbOpBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    TbOpBigtraderOi selectByPrimaryKey(TbOpBigtraderOiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbOpBigtraderOi record, @Param("example") TbOpBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExample(@Param("record") TbOpBigtraderOi record, @Param("example") TbOpBigtraderOiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKeySelective(TbOpBigtraderOi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_BIGTRADER_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKey(TbOpBigtraderOi record);
}