package taifex.model.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import taifex.model.entity.TbOpIns;
import taifex.model.entity.TbOpInsExample;
import taifex.model.entity.TbOpInsKey;

public interface TbOpInsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int countByExample(TbOpInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByExample(TbOpInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int deleteByPrimaryKey(TbOpInsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insert(TbOpIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int insertSelective(TbOpIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    List<TbOpIns> selectByExample(TbOpInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    TbOpIns selectByPrimaryKey(TbOpInsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbOpIns record, @Param("example") TbOpInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByExample(@Param("record") TbOpIns record, @Param("example") TbOpInsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKeySelective(TbOpIns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database name APP.TB_OP_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    int updateByPrimaryKey(TbOpIns record);
}