package taifex.model.entity;

public class TbContractOut extends TbContractOutKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_CONTRACT_OUT.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_CONTRACT_OUT.PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_CONTRACT_OUT.CONTRACT_NAME
     *
     * @return the value of APP.TB_CONTRACT_OUT.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_CONTRACT_OUT.CONTRACT_NAME
     *
     * @param contractName the value for APP.TB_CONTRACT_OUT.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_CONTRACT_OUT.PRICE
     *
     * @return the value of APP.TB_CONTRACT_OUT.PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_CONTRACT_OUT.PRICE
     *
     * @param price the value for APP.TB_CONTRACT_OUT.PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}