package taifex.model.entity;

import java.util.Date;

public class TbFutureHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer contractMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.CONTRACT
     *
     * @return the value of APP.TB_FUTURE_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.CONTRACT
     *
     * @param contract the value for APP.TB_FUTURE_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.CONTRACT_MONTH
     *
     * @return the value of APP.TB_FUTURE_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getContractMonth() {
        return contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.CONTRACT_MONTH
     *
     * @param contractMonth the value for APP.TB_FUTURE_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContractMonth(Integer contractMonth) {
        this.contractMonth = contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.DATE
     *
     * @return the value of APP.TB_FUTURE_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.DATE
     *
     * @param date the value for APP.TB_FUTURE_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }
}