package taifex.model.entity;

public class TbFutureIns extends TbFutureInsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.BUY_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer buyAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.BUY_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer buyCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.SELL_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer sellAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.SELL_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer sellCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.CNT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer cntNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.AMT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer amtNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.BUY_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer buyOiCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.BUY_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer buyOiAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.SELL_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer sellOiCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.SELL_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer sellOiAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.CNT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer cntOiNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_INS.AMT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer amtOiNet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.BUY_AMT
     *
     * @return the value of APP.TB_FUTURE_INS.BUY_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getBuyAmt() {
        return buyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.BUY_AMT
     *
     * @param buyAmt the value for APP.TB_FUTURE_INS.BUY_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setBuyAmt(Integer buyAmt) {
        this.buyAmt = buyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.BUY_CNT
     *
     * @return the value of APP.TB_FUTURE_INS.BUY_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getBuyCnt() {
        return buyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.BUY_CNT
     *
     * @param buyCnt the value for APP.TB_FUTURE_INS.BUY_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setBuyCnt(Integer buyCnt) {
        this.buyCnt = buyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.SELL_AMT
     *
     * @return the value of APP.TB_FUTURE_INS.SELL_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getSellAmt() {
        return sellAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.SELL_AMT
     *
     * @param sellAmt the value for APP.TB_FUTURE_INS.SELL_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSellAmt(Integer sellAmt) {
        this.sellAmt = sellAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.SELL_CNT
     *
     * @return the value of APP.TB_FUTURE_INS.SELL_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getSellCnt() {
        return sellCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.SELL_CNT
     *
     * @param sellCnt the value for APP.TB_FUTURE_INS.SELL_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSellCnt(Integer sellCnt) {
        this.sellCnt = sellCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.CNT_NET
     *
     * @return the value of APP.TB_FUTURE_INS.CNT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getCntNet() {
        return cntNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.CNT_NET
     *
     * @param cntNet the value for APP.TB_FUTURE_INS.CNT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setCntNet(Integer cntNet) {
        this.cntNet = cntNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.AMT_NET
     *
     * @return the value of APP.TB_FUTURE_INS.AMT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getAmtNet() {
        return amtNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.AMT_NET
     *
     * @param amtNet the value for APP.TB_FUTURE_INS.AMT_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setAmtNet(Integer amtNet) {
        this.amtNet = amtNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.BUY_OI_CNT
     *
     * @return the value of APP.TB_FUTURE_INS.BUY_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getBuyOiCnt() {
        return buyOiCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.BUY_OI_CNT
     *
     * @param buyOiCnt the value for APP.TB_FUTURE_INS.BUY_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setBuyOiCnt(Integer buyOiCnt) {
        this.buyOiCnt = buyOiCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.BUY_OI_AMT
     *
     * @return the value of APP.TB_FUTURE_INS.BUY_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getBuyOiAmt() {
        return buyOiAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.BUY_OI_AMT
     *
     * @param buyOiAmt the value for APP.TB_FUTURE_INS.BUY_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setBuyOiAmt(Integer buyOiAmt) {
        this.buyOiAmt = buyOiAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.SELL_OI_CNT
     *
     * @return the value of APP.TB_FUTURE_INS.SELL_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getSellOiCnt() {
        return sellOiCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.SELL_OI_CNT
     *
     * @param sellOiCnt the value for APP.TB_FUTURE_INS.SELL_OI_CNT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSellOiCnt(Integer sellOiCnt) {
        this.sellOiCnt = sellOiCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.SELL_OI_AMT
     *
     * @return the value of APP.TB_FUTURE_INS.SELL_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getSellOiAmt() {
        return sellOiAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.SELL_OI_AMT
     *
     * @param sellOiAmt the value for APP.TB_FUTURE_INS.SELL_OI_AMT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSellOiAmt(Integer sellOiAmt) {
        this.sellOiAmt = sellOiAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.CNT_OI_NET
     *
     * @return the value of APP.TB_FUTURE_INS.CNT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getCntOiNet() {
        return cntOiNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.CNT_OI_NET
     *
     * @param cntOiNet the value for APP.TB_FUTURE_INS.CNT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setCntOiNet(Integer cntOiNet) {
        this.cntOiNet = cntOiNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_INS.AMT_OI_NET
     *
     * @return the value of APP.TB_FUTURE_INS.AMT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getAmtOiNet() {
        return amtOiNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_INS.AMT_OI_NET
     *
     * @param amtOiNet the value for APP.TB_FUTURE_INS.AMT_OI_NET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setAmtOiNet(Integer amtOiNet) {
        this.amtOiNet = amtOiNet;
    }
}