package taifex.model.entity;

public class TbFutureBigtraderOi extends TbFutureBigtraderOiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer top5BuyOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer top5SellOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer top10BuyOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer top10SellOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_BIGTRADER_OI.WHOLE_MARKET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer wholeMarket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.CONTRACT_NAME
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.CONTRACT_NAME
     *
     * @param contractName the value for APP.TB_FUTURE_BIGTRADER_OI.CONTRACT_NAME
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_BUY_OI
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.TOP5_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getTop5BuyOi() {
        return top5BuyOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_BUY_OI
     *
     * @param top5BuyOi the value for APP.TB_FUTURE_BIGTRADER_OI.TOP5_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTop5BuyOi(Integer top5BuyOi) {
        this.top5BuyOi = top5BuyOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_SELL_OI
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.TOP5_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getTop5SellOi() {
        return top5SellOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP5_SELL_OI
     *
     * @param top5SellOi the value for APP.TB_FUTURE_BIGTRADER_OI.TOP5_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTop5SellOi(Integer top5SellOi) {
        this.top5SellOi = top5SellOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_BUY_OI
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.TOP10_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getTop10BuyOi() {
        return top10BuyOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_BUY_OI
     *
     * @param top10BuyOi the value for APP.TB_FUTURE_BIGTRADER_OI.TOP10_BUY_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTop10BuyOi(Integer top10BuyOi) {
        this.top10BuyOi = top10BuyOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_SELL_OI
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.TOP10_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getTop10SellOi() {
        return top10SellOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.TOP10_SELL_OI
     *
     * @param top10SellOi the value for APP.TB_FUTURE_BIGTRADER_OI.TOP10_SELL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTop10SellOi(Integer top10SellOi) {
        this.top10SellOi = top10SellOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_BIGTRADER_OI.WHOLE_MARKET
     *
     * @return the value of APP.TB_FUTURE_BIGTRADER_OI.WHOLE_MARKET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getWholeMarket() {
        return wholeMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_BIGTRADER_OI.WHOLE_MARKET
     *
     * @param wholeMarket the value for APP.TB_FUTURE_BIGTRADER_OI.WHOLE_MARKET
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setWholeMarket(Integer wholeMarket) {
        this.wholeMarket = wholeMarket;
    }
}