package taifex.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbFutureInsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public TbFutureInsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDateIsNull() {
            addCriterion("\"DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("\"DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterionForJDBCDate("\"DATE\" =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"DATE\" <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"DATE\" >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DATE\" >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterionForJDBCDate("\"DATE\" <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DATE\" <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterionForJDBCDate("\"DATE\" in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"DATE\" not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DATE\" between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DATE\" not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andContractIsNull() {
            addCriterion("\"CONTRACT\" is null");
            return (Criteria) this;
        }

        public Criteria andContractIsNotNull() {
            addCriterion("\"CONTRACT\" is not null");
            return (Criteria) this;
        }

        public Criteria andContractEqualTo(String value) {
            addCriterion("\"CONTRACT\" =", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotEqualTo(String value) {
            addCriterion("\"CONTRACT\" <>", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThan(String value) {
            addCriterion("\"CONTRACT\" >", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThanOrEqualTo(String value) {
            addCriterion("\"CONTRACT\" >=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThan(String value) {
            addCriterion("\"CONTRACT\" <", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThanOrEqualTo(String value) {
            addCriterion("\"CONTRACT\" <=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLike(String value) {
            addCriterion("\"CONTRACT\" like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotLike(String value) {
            addCriterion("\"CONTRACT\" not like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractIn(List<String> values) {
            addCriterion("\"CONTRACT\" in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotIn(List<String> values) {
            addCriterion("\"CONTRACT\" not in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractBetween(String value1, String value2) {
            addCriterion("\"CONTRACT\" between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotBetween(String value1, String value2) {
            addCriterion("\"CONTRACT\" not between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andTraderTypeIsNull() {
            addCriterion("\"TRADER_TYPE\" is null");
            return (Criteria) this;
        }

        public Criteria andTraderTypeIsNotNull() {
            addCriterion("\"TRADER_TYPE\" is not null");
            return (Criteria) this;
        }

        public Criteria andTraderTypeEqualTo(String value) {
            addCriterion("\"TRADER_TYPE\" =", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeNotEqualTo(String value) {
            addCriterion("\"TRADER_TYPE\" <>", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeGreaterThan(String value) {
            addCriterion("\"TRADER_TYPE\" >", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("\"TRADER_TYPE\" >=", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeLessThan(String value) {
            addCriterion("\"TRADER_TYPE\" <", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeLessThanOrEqualTo(String value) {
            addCriterion("\"TRADER_TYPE\" <=", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeLike(String value) {
            addCriterion("\"TRADER_TYPE\" like", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeNotLike(String value) {
            addCriterion("\"TRADER_TYPE\" not like", value, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeIn(List<String> values) {
            addCriterion("\"TRADER_TYPE\" in", values, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeNotIn(List<String> values) {
            addCriterion("\"TRADER_TYPE\" not in", values, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeBetween(String value1, String value2) {
            addCriterion("\"TRADER_TYPE\" between", value1, value2, "traderType");
            return (Criteria) this;
        }

        public Criteria andTraderTypeNotBetween(String value1, String value2) {
            addCriterion("\"TRADER_TYPE\" not between", value1, value2, "traderType");
            return (Criteria) this;
        }

        public Criteria andBuyAmtIsNull() {
            addCriterion("\"BUY_AMT\" is null");
            return (Criteria) this;
        }

        public Criteria andBuyAmtIsNotNull() {
            addCriterion("\"BUY_AMT\" is not null");
            return (Criteria) this;
        }

        public Criteria andBuyAmtEqualTo(Integer value) {
            addCriterion("\"BUY_AMT\" =", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtNotEqualTo(Integer value) {
            addCriterion("\"BUY_AMT\" <>", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtGreaterThan(Integer value) {
            addCriterion("\"BUY_AMT\" >", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_AMT\" >=", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtLessThan(Integer value) {
            addCriterion("\"BUY_AMT\" <", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtLessThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_AMT\" <=", value, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtIn(List<Integer> values) {
            addCriterion("\"BUY_AMT\" in", values, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtNotIn(List<Integer> values) {
            addCriterion("\"BUY_AMT\" not in", values, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_AMT\" between", value1, value2, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyAmtNotBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_AMT\" not between", value1, value2, "buyAmt");
            return (Criteria) this;
        }

        public Criteria andBuyCntIsNull() {
            addCriterion("\"BUY_CNT\" is null");
            return (Criteria) this;
        }

        public Criteria andBuyCntIsNotNull() {
            addCriterion("\"BUY_CNT\" is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCntEqualTo(Integer value) {
            addCriterion("\"BUY_CNT\" =", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotEqualTo(Integer value) {
            addCriterion("\"BUY_CNT\" <>", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntGreaterThan(Integer value) {
            addCriterion("\"BUY_CNT\" >", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_CNT\" >=", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntLessThan(Integer value) {
            addCriterion("\"BUY_CNT\" <", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntLessThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_CNT\" <=", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntIn(List<Integer> values) {
            addCriterion("\"BUY_CNT\" in", values, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotIn(List<Integer> values) {
            addCriterion("\"BUY_CNT\" not in", values, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_CNT\" between", value1, value2, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_CNT\" not between", value1, value2, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andSellAmtIsNull() {
            addCriterion("\"SELL_AMT\" is null");
            return (Criteria) this;
        }

        public Criteria andSellAmtIsNotNull() {
            addCriterion("\"SELL_AMT\" is not null");
            return (Criteria) this;
        }

        public Criteria andSellAmtEqualTo(Integer value) {
            addCriterion("\"SELL_AMT\" =", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtNotEqualTo(Integer value) {
            addCriterion("\"SELL_AMT\" <>", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtGreaterThan(Integer value) {
            addCriterion("\"SELL_AMT\" >", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_AMT\" >=", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtLessThan(Integer value) {
            addCriterion("\"SELL_AMT\" <", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtLessThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_AMT\" <=", value, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtIn(List<Integer> values) {
            addCriterion("\"SELL_AMT\" in", values, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtNotIn(List<Integer> values) {
            addCriterion("\"SELL_AMT\" not in", values, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_AMT\" between", value1, value2, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellAmtNotBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_AMT\" not between", value1, value2, "sellAmt");
            return (Criteria) this;
        }

        public Criteria andSellCntIsNull() {
            addCriterion("\"SELL_CNT\" is null");
            return (Criteria) this;
        }

        public Criteria andSellCntIsNotNull() {
            addCriterion("\"SELL_CNT\" is not null");
            return (Criteria) this;
        }

        public Criteria andSellCntEqualTo(Integer value) {
            addCriterion("\"SELL_CNT\" =", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntNotEqualTo(Integer value) {
            addCriterion("\"SELL_CNT\" <>", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntGreaterThan(Integer value) {
            addCriterion("\"SELL_CNT\" >", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_CNT\" >=", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntLessThan(Integer value) {
            addCriterion("\"SELL_CNT\" <", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntLessThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_CNT\" <=", value, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntIn(List<Integer> values) {
            addCriterion("\"SELL_CNT\" in", values, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntNotIn(List<Integer> values) {
            addCriterion("\"SELL_CNT\" not in", values, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_CNT\" between", value1, value2, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andSellCntNotBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_CNT\" not between", value1, value2, "sellCnt");
            return (Criteria) this;
        }

        public Criteria andCntNetIsNull() {
            addCriterion("\"CNT_NET\" is null");
            return (Criteria) this;
        }

        public Criteria andCntNetIsNotNull() {
            addCriterion("\"CNT_NET\" is not null");
            return (Criteria) this;
        }

        public Criteria andCntNetEqualTo(Integer value) {
            addCriterion("\"CNT_NET\" =", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetNotEqualTo(Integer value) {
            addCriterion("\"CNT_NET\" <>", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetGreaterThan(Integer value) {
            addCriterion("\"CNT_NET\" >", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"CNT_NET\" >=", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetLessThan(Integer value) {
            addCriterion("\"CNT_NET\" <", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetLessThanOrEqualTo(Integer value) {
            addCriterion("\"CNT_NET\" <=", value, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetIn(List<Integer> values) {
            addCriterion("\"CNT_NET\" in", values, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetNotIn(List<Integer> values) {
            addCriterion("\"CNT_NET\" not in", values, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetBetween(Integer value1, Integer value2) {
            addCriterion("\"CNT_NET\" between", value1, value2, "cntNet");
            return (Criteria) this;
        }

        public Criteria andCntNetNotBetween(Integer value1, Integer value2) {
            addCriterion("\"CNT_NET\" not between", value1, value2, "cntNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetIsNull() {
            addCriterion("\"AMT_NET\" is null");
            return (Criteria) this;
        }

        public Criteria andAmtNetIsNotNull() {
            addCriterion("\"AMT_NET\" is not null");
            return (Criteria) this;
        }

        public Criteria andAmtNetEqualTo(Integer value) {
            addCriterion("\"AMT_NET\" =", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetNotEqualTo(Integer value) {
            addCriterion("\"AMT_NET\" <>", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetGreaterThan(Integer value) {
            addCriterion("\"AMT_NET\" >", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"AMT_NET\" >=", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetLessThan(Integer value) {
            addCriterion("\"AMT_NET\" <", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetLessThanOrEqualTo(Integer value) {
            addCriterion("\"AMT_NET\" <=", value, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetIn(List<Integer> values) {
            addCriterion("\"AMT_NET\" in", values, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetNotIn(List<Integer> values) {
            addCriterion("\"AMT_NET\" not in", values, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetBetween(Integer value1, Integer value2) {
            addCriterion("\"AMT_NET\" between", value1, value2, "amtNet");
            return (Criteria) this;
        }

        public Criteria andAmtNetNotBetween(Integer value1, Integer value2) {
            addCriterion("\"AMT_NET\" not between", value1, value2, "amtNet");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntIsNull() {
            addCriterion("\"BUY_OI_CNT\" is null");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntIsNotNull() {
            addCriterion("\"BUY_OI_CNT\" is not null");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntEqualTo(Integer value) {
            addCriterion("\"BUY_OI_CNT\" =", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntNotEqualTo(Integer value) {
            addCriterion("\"BUY_OI_CNT\" <>", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntGreaterThan(Integer value) {
            addCriterion("\"BUY_OI_CNT\" >", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_OI_CNT\" >=", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntLessThan(Integer value) {
            addCriterion("\"BUY_OI_CNT\" <", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntLessThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_OI_CNT\" <=", value, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntIn(List<Integer> values) {
            addCriterion("\"BUY_OI_CNT\" in", values, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntNotIn(List<Integer> values) {
            addCriterion("\"BUY_OI_CNT\" not in", values, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_OI_CNT\" between", value1, value2, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiCntNotBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_OI_CNT\" not between", value1, value2, "buyOiCnt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtIsNull() {
            addCriterion("\"BUY_OI_AMT\" is null");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtIsNotNull() {
            addCriterion("\"BUY_OI_AMT\" is not null");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtEqualTo(Integer value) {
            addCriterion("\"BUY_OI_AMT\" =", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtNotEqualTo(Integer value) {
            addCriterion("\"BUY_OI_AMT\" <>", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtGreaterThan(Integer value) {
            addCriterion("\"BUY_OI_AMT\" >", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_OI_AMT\" >=", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtLessThan(Integer value) {
            addCriterion("\"BUY_OI_AMT\" <", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtLessThanOrEqualTo(Integer value) {
            addCriterion("\"BUY_OI_AMT\" <=", value, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtIn(List<Integer> values) {
            addCriterion("\"BUY_OI_AMT\" in", values, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtNotIn(List<Integer> values) {
            addCriterion("\"BUY_OI_AMT\" not in", values, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_OI_AMT\" between", value1, value2, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andBuyOiAmtNotBetween(Integer value1, Integer value2) {
            addCriterion("\"BUY_OI_AMT\" not between", value1, value2, "buyOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntIsNull() {
            addCriterion("\"SELL_OI_CNT\" is null");
            return (Criteria) this;
        }

        public Criteria andSellOiCntIsNotNull() {
            addCriterion("\"SELL_OI_CNT\" is not null");
            return (Criteria) this;
        }

        public Criteria andSellOiCntEqualTo(Integer value) {
            addCriterion("\"SELL_OI_CNT\" =", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntNotEqualTo(Integer value) {
            addCriterion("\"SELL_OI_CNT\" <>", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntGreaterThan(Integer value) {
            addCriterion("\"SELL_OI_CNT\" >", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_OI_CNT\" >=", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntLessThan(Integer value) {
            addCriterion("\"SELL_OI_CNT\" <", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntLessThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_OI_CNT\" <=", value, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntIn(List<Integer> values) {
            addCriterion("\"SELL_OI_CNT\" in", values, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntNotIn(List<Integer> values) {
            addCriterion("\"SELL_OI_CNT\" not in", values, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_OI_CNT\" between", value1, value2, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiCntNotBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_OI_CNT\" not between", value1, value2, "sellOiCnt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtIsNull() {
            addCriterion("\"SELL_OI_AMT\" is null");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtIsNotNull() {
            addCriterion("\"SELL_OI_AMT\" is not null");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtEqualTo(Integer value) {
            addCriterion("\"SELL_OI_AMT\" =", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtNotEqualTo(Integer value) {
            addCriterion("\"SELL_OI_AMT\" <>", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtGreaterThan(Integer value) {
            addCriterion("\"SELL_OI_AMT\" >", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_OI_AMT\" >=", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtLessThan(Integer value) {
            addCriterion("\"SELL_OI_AMT\" <", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtLessThanOrEqualTo(Integer value) {
            addCriterion("\"SELL_OI_AMT\" <=", value, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtIn(List<Integer> values) {
            addCriterion("\"SELL_OI_AMT\" in", values, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtNotIn(List<Integer> values) {
            addCriterion("\"SELL_OI_AMT\" not in", values, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_OI_AMT\" between", value1, value2, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andSellOiAmtNotBetween(Integer value1, Integer value2) {
            addCriterion("\"SELL_OI_AMT\" not between", value1, value2, "sellOiAmt");
            return (Criteria) this;
        }

        public Criteria andCntOiNetIsNull() {
            addCriterion("\"CNT_OI_NET\" is null");
            return (Criteria) this;
        }

        public Criteria andCntOiNetIsNotNull() {
            addCriterion("\"CNT_OI_NET\" is not null");
            return (Criteria) this;
        }

        public Criteria andCntOiNetEqualTo(Integer value) {
            addCriterion("\"CNT_OI_NET\" =", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetNotEqualTo(Integer value) {
            addCriterion("\"CNT_OI_NET\" <>", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetGreaterThan(Integer value) {
            addCriterion("\"CNT_OI_NET\" >", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"CNT_OI_NET\" >=", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetLessThan(Integer value) {
            addCriterion("\"CNT_OI_NET\" <", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetLessThanOrEqualTo(Integer value) {
            addCriterion("\"CNT_OI_NET\" <=", value, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetIn(List<Integer> values) {
            addCriterion("\"CNT_OI_NET\" in", values, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetNotIn(List<Integer> values) {
            addCriterion("\"CNT_OI_NET\" not in", values, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetBetween(Integer value1, Integer value2) {
            addCriterion("\"CNT_OI_NET\" between", value1, value2, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andCntOiNetNotBetween(Integer value1, Integer value2) {
            addCriterion("\"CNT_OI_NET\" not between", value1, value2, "cntOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetIsNull() {
            addCriterion("\"AMT_OI_NET\" is null");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetIsNotNull() {
            addCriterion("\"AMT_OI_NET\" is not null");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetEqualTo(Integer value) {
            addCriterion("\"AMT_OI_NET\" =", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetNotEqualTo(Integer value) {
            addCriterion("\"AMT_OI_NET\" <>", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetGreaterThan(Integer value) {
            addCriterion("\"AMT_OI_NET\" >", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"AMT_OI_NET\" >=", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetLessThan(Integer value) {
            addCriterion("\"AMT_OI_NET\" <", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetLessThanOrEqualTo(Integer value) {
            addCriterion("\"AMT_OI_NET\" <=", value, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetIn(List<Integer> values) {
            addCriterion("\"AMT_OI_NET\" in", values, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetNotIn(List<Integer> values) {
            addCriterion("\"AMT_OI_NET\" not in", values, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetBetween(Integer value1, Integer value2) {
            addCriterion("\"AMT_OI_NET\" between", value1, value2, "amtOiNet");
            return (Criteria) this;
        }

        public Criteria andAmtOiNetNotBetween(Integer value1, Integer value2) {
            addCriterion("\"AMT_OI_NET\" not between", value1, value2, "amtOiNet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 04 17:46:10 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP.TB_FUTURE_INS
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}