package taifex.model.entity;

public class TbFutureHis extends TbFutureHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.UPDOWN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer updownPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.UPDOWN_PERCENT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double updownPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer highPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer volumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer settlePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer oi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_FUTURE_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer openPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.CLOSE_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.CLOSE_PRICE
     *
     * @param closePrice the value for APP.TB_FUTURE_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setClosePrice(Integer closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.UPDOWN_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.UPDOWN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getUpdownPrice() {
        return updownPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.UPDOWN_PRICE
     *
     * @param updownPrice the value for APP.TB_FUTURE_HIS.UPDOWN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setUpdownPrice(Integer updownPrice) {
        this.updownPrice = updownPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.UPDOWN_PERCENT
     *
     * @return the value of APP.TB_FUTURE_HIS.UPDOWN_PERCENT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getUpdownPercent() {
        return updownPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.UPDOWN_PERCENT
     *
     * @param updownPercent the value for APP.TB_FUTURE_HIS.UPDOWN_PERCENT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setUpdownPercent(Double updownPercent) {
        this.updownPercent = updownPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.HIGH_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.HIGH_PRICE
     *
     * @param highPrice the value for APP.TB_FUTURE_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setHighPrice(Integer highPrice) {
        this.highPrice = highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.VOLUMN
     *
     * @return the value of APP.TB_FUTURE_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.VOLUMN
     *
     * @param volumn the value for APP.TB_FUTURE_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setVolumn(Integer volumn) {
        this.volumn = volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.SETTLE_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getSettlePrice() {
        return settlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.SETTLE_PRICE
     *
     * @param settlePrice the value for APP.TB_FUTURE_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSettlePrice(Integer settlePrice) {
        this.settlePrice = settlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.LOW_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.LOW_PRICE
     *
     * @param lowPrice the value for APP.TB_FUTURE_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setLowPrice(Integer lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.OI
     *
     * @return the value of APP.TB_FUTURE_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getOi() {
        return oi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.OI
     *
     * @param oi the value for APP.TB_FUTURE_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOi(Integer oi) {
        this.oi = oi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_FUTURE_HIS.OPEN_PRICE
     *
     * @return the value of APP.TB_FUTURE_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_FUTURE_HIS.OPEN_PRICE
     *
     * @param openPrice the value for APP.TB_FUTURE_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOpenPrice(Integer openPrice) {
        this.openPrice = openPrice;
    }
}