package taifex.model.entity;

public class TbOpHis extends TbOpHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double highPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer volumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double settlePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer oi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.LAST_BUY_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double lastBuyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.LAST_SELL_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double lastSellPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.HIGH_PRICE
     *
     * @return the value of APP.TB_OP_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.HIGH_PRICE
     *
     * @param highPrice the value for APP.TB_OP_HIS.HIGH_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setHighPrice(Double highPrice) {
        this.highPrice = highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.LOW_PRICE
     *
     * @return the value of APP.TB_OP_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.LOW_PRICE
     *
     * @param lowPrice the value for APP.TB_OP_HIS.LOW_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setLowPrice(Double lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.CLOSE_PRICE
     *
     * @return the value of APP.TB_OP_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.CLOSE_PRICE
     *
     * @param closePrice the value for APP.TB_OP_HIS.CLOSE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setClosePrice(Double closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.VOLUMN
     *
     * @return the value of APP.TB_OP_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.VOLUMN
     *
     * @param volumn the value for APP.TB_OP_HIS.VOLUMN
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setVolumn(Integer volumn) {
        this.volumn = volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.OPEN_PRICE
     *
     * @return the value of APP.TB_OP_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.OPEN_PRICE
     *
     * @param openPrice the value for APP.TB_OP_HIS.OPEN_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOpenPrice(Double openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.SETTLE_PRICE
     *
     * @return the value of APP.TB_OP_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getSettlePrice() {
        return settlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.SETTLE_PRICE
     *
     * @param settlePrice the value for APP.TB_OP_HIS.SETTLE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setSettlePrice(Double settlePrice) {
        this.settlePrice = settlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.OI
     *
     * @return the value of APP.TB_OP_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getOi() {
        return oi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.OI
     *
     * @param oi the value for APP.TB_OP_HIS.OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOi(Integer oi) {
        this.oi = oi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.LAST_BUY_PRICE
     *
     * @return the value of APP.TB_OP_HIS.LAST_BUY_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getLastBuyPrice() {
        return lastBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.LAST_BUY_PRICE
     *
     * @param lastBuyPrice the value for APP.TB_OP_HIS.LAST_BUY_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setLastBuyPrice(Double lastBuyPrice) {
        this.lastBuyPrice = lastBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.LAST_SELL_PRICE
     *
     * @return the value of APP.TB_OP_HIS.LAST_SELL_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getLastSellPrice() {
        return lastSellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.LAST_SELL_PRICE
     *
     * @param lastSellPrice the value for APP.TB_OP_HIS.LAST_SELL_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setLastSellPrice(Double lastSellPrice) {
        this.lastSellPrice = lastSellPrice;
    }
}