package taifex.model.entity;

import java.util.Date;

public class TbOpBigtraderOiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_BIGTRADER_OI.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_BIGTRADER_OI.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_BIGTRADER_OI.PUT_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String putCall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_BIGTRADER_OI.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contractMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_BIGTRADER_OI.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String traderType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_BIGTRADER_OI.DATE
     *
     * @return the value of APP.TB_OP_BIGTRADER_OI.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_BIGTRADER_OI.DATE
     *
     * @param date the value for APP.TB_OP_BIGTRADER_OI.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_BIGTRADER_OI.CONTRACT
     *
     * @return the value of APP.TB_OP_BIGTRADER_OI.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_BIGTRADER_OI.CONTRACT
     *
     * @param contract the value for APP.TB_OP_BIGTRADER_OI.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_BIGTRADER_OI.PUT_CALL
     *
     * @return the value of APP.TB_OP_BIGTRADER_OI.PUT_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getPutCall() {
        return putCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_BIGTRADER_OI.PUT_CALL
     *
     * @param putCall the value for APP.TB_OP_BIGTRADER_OI.PUT_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPutCall(String putCall) {
        this.putCall = putCall == null ? null : putCall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_BIGTRADER_OI.CONTRACT_MONTH
     *
     * @return the value of APP.TB_OP_BIGTRADER_OI.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContractMonth() {
        return contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_BIGTRADER_OI.CONTRACT_MONTH
     *
     * @param contractMonth the value for APP.TB_OP_BIGTRADER_OI.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContractMonth(String contractMonth) {
        this.contractMonth = contractMonth == null ? null : contractMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_BIGTRADER_OI.TRADER_TYPE
     *
     * @return the value of APP.TB_OP_BIGTRADER_OI.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getTraderType() {
        return traderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_BIGTRADER_OI.TRADER_TYPE
     *
     * @param traderType the value for APP.TB_OP_BIGTRADER_OI.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTraderType(String traderType) {
        this.traderType = traderType == null ? null : traderType.trim();
    }
}