package taifex.model.entity;

import java.util.Date;

public class TbOpInsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_INS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_INS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_INS.BUY_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String buyCall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_INS.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String traderType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_INS.DATE
     *
     * @return the value of APP.TB_OP_INS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_INS.DATE
     *
     * @param date the value for APP.TB_OP_INS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_INS.CONTRACT
     *
     * @return the value of APP.TB_OP_INS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_INS.CONTRACT
     *
     * @param contract the value for APP.TB_OP_INS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_INS.BUY_CALL
     *
     * @return the value of APP.TB_OP_INS.BUY_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getBuyCall() {
        return buyCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_INS.BUY_CALL
     *
     * @param buyCall the value for APP.TB_OP_INS.BUY_CALL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setBuyCall(String buyCall) {
        this.buyCall = buyCall == null ? null : buyCall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_INS.TRADER_TYPE
     *
     * @return the value of APP.TB_OP_INS.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getTraderType() {
        return traderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_INS.TRADER_TYPE
     *
     * @param traderType the value for APP.TB_OP_INS.TRADER_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setTraderType(String traderType) {
        this.traderType = traderType == null ? null : traderType.trim();
    }
}