package taifex.model.entity;

import java.util.Date;

public class TbOpHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.EXCERCISE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer excercisePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String contractMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_OP_HIS.OPTION_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private String optionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.CONTRACT
     *
     * @return the value of APP.TB_OP_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.CONTRACT
     *
     * @param contract the value for APP.TB_OP_HIS.CONTRACT
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.EXCERCISE_PRICE
     *
     * @return the value of APP.TB_OP_HIS.EXCERCISE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getExcercisePrice() {
        return excercisePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.EXCERCISE_PRICE
     *
     * @param excercisePrice the value for APP.TB_OP_HIS.EXCERCISE_PRICE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setExcercisePrice(Integer excercisePrice) {
        this.excercisePrice = excercisePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.CONTRACT_MONTH
     *
     * @return the value of APP.TB_OP_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getContractMonth() {
        return contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.CONTRACT_MONTH
     *
     * @param contractMonth the value for APP.TB_OP_HIS.CONTRACT_MONTH
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setContractMonth(String contractMonth) {
        this.contractMonth = contractMonth == null ? null : contractMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.DATE
     *
     * @return the value of APP.TB_OP_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.DATE
     *
     * @param date the value for APP.TB_OP_HIS.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_OP_HIS.OPTION_TYPE
     *
     * @return the value of APP.TB_OP_HIS.OPTION_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_OP_HIS.OPTION_TYPE
     *
     * @param optionType the value for APP.TB_OP_HIS.OPTION_TYPE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setOptionType(String optionType) {
        this.optionType = optionType == null ? null : optionType.trim();
    }
}