package taifex.model.entity;

import java.util.Date;

public class TbPutCallRatio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.PUT_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer putVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.CALL_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer callVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATION_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double putCallRationVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.PUT_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer putOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.CALL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Integer callOi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATIO_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    private Double putCallRatioOi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.DATE
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.DATE
     *
     * @param date the value for APP.TB_PUT_CALL_RATIO.DATE
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.PUT_VOL
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.PUT_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getPutVol() {
        return putVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.PUT_VOL
     *
     * @param putVol the value for APP.TB_PUT_CALL_RATIO.PUT_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPutVol(Integer putVol) {
        this.putVol = putVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.CALL_VOL
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.CALL_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getCallVol() {
        return callVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.CALL_VOL
     *
     * @param callVol the value for APP.TB_PUT_CALL_RATIO.CALL_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setCallVol(Integer callVol) {
        this.callVol = callVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATION_VOL
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.PUT_CALL_RATION_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getPutCallRationVol() {
        return putCallRationVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATION_VOL
     *
     * @param putCallRationVol the value for APP.TB_PUT_CALL_RATIO.PUT_CALL_RATION_VOL
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPutCallRationVol(Double putCallRationVol) {
        this.putCallRationVol = putCallRationVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.PUT_OI
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.PUT_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getPutOi() {
        return putOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.PUT_OI
     *
     * @param putOi the value for APP.TB_PUT_CALL_RATIO.PUT_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPutOi(Integer putOi) {
        this.putOi = putOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.CALL_OI
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.CALL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Integer getCallOi() {
        return callOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.CALL_OI
     *
     * @param callOi the value for APP.TB_PUT_CALL_RATIO.CALL_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setCallOi(Integer callOi) {
        this.callOi = callOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATIO_OI
     *
     * @return the value of APP.TB_PUT_CALL_RATIO.PUT_CALL_RATIO_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public Double getPutCallRatioOi() {
        return putCallRatioOi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.TB_PUT_CALL_RATIO.PUT_CALL_RATIO_OI
     *
     * @param putCallRatioOi the value for APP.TB_PUT_CALL_RATIO.PUT_CALL_RATIO_OI
     *
     * @mbggenerated Wed Mar 04 17:46:10 CST 2015
     */
    public void setPutCallRatioOi(Double putCallRatioOi) {
        this.putCallRatioOi = putCallRatioOi;
    }
}